#!{{pkgPathFor "core/bash"}}/bin/bash

# Allows to see errors as they occur
exec 2>&1

echo "Executing init hook"

ln -fs {{pkg.path}}/app {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/instance {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/wsgi.py {{pkg.svc_var_path}}i
ln -fs {{pkg.path}}/manage.py {{pkg.svc_var_path}}

echo "Creating database superuser"
source {{pkg.svc_config_path}}/helpers.sh
# create db superuser
create_db_superuser
# set up data directory for pgsql service
if [ ! -d "{{cfg.db.datapath}}" ]; then
    setup_db_datapath
else
    echo "Data dir already exists"
fi

# set var, data dir permissions for superuser
# set_dir_permissions

# initialize db cluster
init_db_cluster



