#!/bin/bash -xe

# Allows to see errors as they occur
exec 2>&1

echo "Executing init hook"

ln -fs {{pkg.path}}/habitat {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/app {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/instance {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/venv {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/*.py {{pkg.svc_var_path}}
