#!/bin/bash -xe

# Allows to see errors as they occur
exec 2>&1

echo "Executing runtime hook ..."

cd {{pkg.path}}

export APP_SETTINGS="production"
export DATABASE_URL=postgresql://localhost:5432/registry

# start the server using gunicorn
exec gunicorn wsgi --bind 0.0.0.0:8080
