create table if not exists physical_address(
	id INT,
	location_id INT,
	address VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	postal_code INT,
	country VARCHAR(2)
);
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (1, 1, '72 Springview Avenue', 'New Bedford', 'Massachusetts', '02745', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (2, 2, '16 Toban Crossing', 'Saginaw', 'Michigan', '48604', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (3, 3, '10 Sachs Crossing', 'Houston', 'Texas', '77281', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (4, 4, '44086 Dennis Way', 'Sparks', 'Nevada', '89436', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (5, 5, '68 Swallow Terrace', 'Dallas', 'Texas', '75342', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (6, 6, '60521 Bartillon Hill', 'Racine', 'Wisconsin', '53405', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (7, 7, '3758 Meadow Valley Point', 'Amarillo', 'Texas', '79116', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (8, 8, '2 Twin Pines Parkway', 'Washington', 'District of Columbia', '20205', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (9, 9, '68309 Maryland Street', 'Columbus', 'Ohio', '43215', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (10, 10, '97923 Hoffman Parkway', 'Las Vegas', 'Nevada', '89120', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (11, 11, '548 Scofield Crossing', 'Saint Petersburg', 'Florida', '33715', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (12, 12, '6 3rd Alley', 'Colorado Springs', 'Colorado', '80935', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (13, 13, '0 Sunnyside Point', 'Pittsburgh', 'Pennsylvania', '15261', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (14, 14, '74 Cardinal Lane', 'Pittsburgh', 'Pennsylvania', '15240', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (15, 15, '3 Gateway Crossing', 'Huntington', 'West Virginia', '25705', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (16, 16, '742 Westerfield Street', 'West Hartford', 'Connecticut', '06127', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (17, 17, '85800 Cascade Pass', 'New York City', 'New York', '10024', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (18, 18, '64612 Ramsey Street', 'Memphis', 'Tennessee', '38131', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (19, 19, '77 Maryland Place', 'Houston', 'Texas', '77234', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (20, 20, '2 Corry Way', 'Baltimore', 'Maryland', '21275', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (21, 21, '403 Washington Park', 'Honolulu', 'Hawaii', '96805', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (22, 22, '11 International Place', 'Flint', 'Michigan', '48550', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (23, 23, '25965 Menomonie Parkway', 'Columbus', 'Ohio', '43240', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (24, 24, '680 Morning Crossing', 'Falls Church', 'Virginia', '22047', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (25, 25, '2 Manufacturers Way', 'Pittsburgh', 'Pennsylvania', '15266', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (26, 26, '80 Sherman Hill', 'Boca Raton', 'Florida', '33487', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (27, 27, '2453 Little Fleur Crossing', 'Akron', 'Ohio', '44310', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (28, 28, '99 Lake View Plaza', 'San Antonio', 'Texas', '78265', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (29, 29, '712 Maywood Junction', 'Baton Rouge', 'Louisiana', '70815', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (30, 30, '86421 Sloan Street', 'Orlando', 'Florida', '32819', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (31, 31, '556 Surrey Crossing', 'Corpus Christi', 'Texas', '78465', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (32, 32, '6 Rigney Place', 'Columbia', 'Missouri', '65211', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (33, 33, '11 Mandrake Avenue', 'Tulsa', 'Oklahoma', '74133', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (34, 34, '17456 Aberg Place', 'Toledo', 'Ohio', '43605', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (35, 35, '02796 Monica Plaza', 'Topeka', 'Kansas', '66611', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (36, 36, '1742 Dorton Terrace', 'Shreveport', 'Louisiana', '71161', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (37, 37, '087 Moose Plaza', 'Fort Worth', 'Texas', '76198', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (38, 38, '616 Ronald Regan Center', 'Pompano Beach', 'Florida', '33064', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (39, 39, '9693 Declaration Court', 'Milwaukee', 'Wisconsin', '53210', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (40, 40, '96 Forster Avenue', 'Las Vegas', 'Nevada', '89135', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (41, 41, '8379 Bellgrove Alley', 'Hartford', 'Connecticut', '06140', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (42, 42, '16715 Scofield Alley', 'Garden Grove', 'California', '92844', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (43, 43, '52 Katie Court', 'Inglewood', 'California', '90398', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (44, 44, '0468 Petterle Center', 'Birmingham', 'Alabama', '35215', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (45, 45, '623 Fisk Drive', 'Fairfax', 'Virginia', '22036', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (46, 46, '640 Claremont Point', 'Sioux Falls', 'South Dakota', '57110', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (47, 47, '5 Bartillon Plaza', 'Mountain View', 'California', '94042', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (48, 48, '57560 Hazelcrest Hill', 'Fort Lauderdale', 'Florida', '33305', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (49, 49, '53193 Straubel Way', 'Maple Plain', 'Minnesota', '55572', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (50, 50, '968 Loomis Junction', 'Laredo', 'Texas', '78044', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (51, 51, '4 Gateway Place', 'Detroit', 'Michigan', '48267', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (52, 52, '7411 Hudson Alley', 'Pittsburgh', 'Pennsylvania', '15266', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (53, 53, '6 Sundown Way', 'Hicksville', 'New York', '11854', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (54, 54, '6 Orin Parkway', 'Biloxi', 'Mississippi', '39534', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (55, 55, '4 Stephen Pass', 'Naperville', 'Illinois', '60567', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (56, 56, '04634 Kedzie Pass', 'Riverside', 'California', '92513', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (57, 57, '56619 Cordelia Point', 'Albuquerque', 'New Mexico', '87180', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (58, 58, '19587 Towne Terrace', 'Albuquerque', 'New Mexico', '87180', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (59, 59, '734 David Road', 'Anchorage', 'Alaska', '99517', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (60, 60, '78 Cascade Junction', 'Port Charlotte', 'Florida', '33954', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (61, 61, '166 Myrtle Drive', 'Los Angeles', 'California', '90050', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (62, 62, '34780 Jenna Point', 'Charlotte', 'North Carolina', '28220', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (63, 63, '05196 Buell Trail', 'Fullerton', 'California', '92640', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (64, 64, '2798 Kingsford Trail', 'Washington', 'District of Columbia', '20057', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (65, 65, '3735 Sommers Terrace', 'Sparks', 'Nevada', '89436', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (66, 66, '98 Mitchell Center', 'El Paso', 'Texas', '88535', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (67, 67, '901 Eastlawn Plaza', 'Bellevue', 'Washington', '98008', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (68, 68, '7676 Packers Parkway', 'Portland', 'Oregon', '97206', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (69, 69, '7521 Crownhardt Crossing', 'Charleston', 'West Virginia', '25336', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (70, 70, '4693 Buhler Street', 'Little Rock', 'Arkansas', '72222', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (71, 71, '4096 Blue Bill Park Avenue', 'Albany', 'New York', '12222', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (72, 72, '8653 Holy Cross Place', 'Saint Louis', 'Missouri', '63121', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (73, 73, '253 Alpine Pass', 'Muskegon', 'Michigan', '49444', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (74, 74, '2453 Sauthoff Way', 'Laredo', 'Texas', '78044', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (75, 75, '8 Kipling Road', 'Erie', 'Pennsylvania', '16522', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (76, 76, '4 Dakota Crossing', 'New Orleans', 'Louisiana', '70174', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (77, 77, '1533 Loftsgordon Parkway', 'Saginaw', 'Michigan', '48609', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (78, 78, '74 Sommers Avenue', 'Winston Salem', 'North Carolina', '27110', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (79, 79, '10 Graceland Circle', 'Maple Plain', 'Minnesota', '55579', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (80, 80, '80 Mariners Cove Trail', 'Saint Louis', 'Missouri', '63131', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (81, 81, '14 Marquette Center', 'Lincoln', 'Nebraska', '68505', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (82, 82, '34387 Lunder Parkway', 'New York City', 'New York', '10203', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (83, 83, '73 Dawn Plaza', 'Jacksonville', 'Florida', '32259', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (84, 84, '5618 Tomscot Point', 'Sacramento', 'California', '94273', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (85, 85, '4 Sherman Road', 'Des Moines', 'Iowa', '50335', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (86, 86, '1 Oak Valley Park', 'Boston', 'Massachusetts', '02163', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (87, 87, '04712 Gale Road', 'Sacramento', 'California', '94297', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (88, 88, '20006 Sachs Center', 'Albuquerque', 'New Mexico', '87121', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (89, 89, '1 Glendale Alley', 'Huntsville', 'Alabama', '35805', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (90, 90, '50584 Warner Street', 'Corpus Christi', 'Texas', '78475', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (91, 91, '7 Mallard Plaza', 'Norwalk', 'Connecticut', '06854', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (92, 92, '80 Dunning Lane', 'Bradenton', 'Florida', '34282', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (93, 93, '2628 Crownhardt Drive', 'Tyler', 'Texas', '75705', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (94, 94, '6816 Lukken Road', 'Phoenix', 'Arizona', '85025', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (95, 95, '8 Fulton Trail', 'Phoenix', 'Arizona', '85015', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (96, 96, '071 Eagan Plaza', 'Waco', 'Texas', '76711', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (97, 97, '386 Rusk Circle', 'Bronx', 'New York', '10469', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (98, 98, '01372 Marquette Circle', 'Honolulu', 'Hawaii', '96840', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (99, 99, '380 Sunnyside Lane', 'Atlanta', 'Georgia', '31106', 'US');
insert into physical_address (id, location_id, address, city, state, postal_code, country) values (100, 100, '42 Sycamore Park', 'Philadelphia', 'Pennsylvania', '19131', 'US');
